import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer";
import Header from "@/components/Header";
import ThemeProvider from "@/components/Theme";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Notary Site",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      
      <body className={inter.className}>
        <ThemeProvider attribute = "class" defaultTheme= "light" />
      <Header/>
        {children}
        <Footer />
        </body>
     
    </html>
  );
}